name: playwright-tests
on: [push]
jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: microsoft/playwright-github-action@v1
      - name: Run your tests
      - run: npm test