name: Test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: SFDigitalServices/wait-for-deployment-action@v1
        id: deployment
        with:
          token: ${{ github.token }}
          environment: Preview
      - name: next-step
        run: echo "Deployed to: ${{ steps.deployment.outputs.url }}"